server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/chating?characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: Password12!
  redis:
    host: localhost
    port: 6379
