server:
  port: 8080
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/chating?characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: Password12!
  redis:
    host: localhost
    port: 6379
