server:
  port: 8000
restTemplate:
  factory:
    readTimeout: 5000
    connectTimeout: 3000
  httpClient:
    maxConnTotal: 100
    maxConnPerRoute: 5
spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false